# Generated by Django 4.2.7 on 2023-11-06 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dreamreal",
            options={},
        ),
    ]
