# Generated by Django 4.2.7 on 2023-11-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_dreamreal_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Online",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domain", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "online",
            },
        ),
    ]
