# Generated by Django 4.2.7 on 2023-11-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_online"),
    ]

    operations = [
        migrations.AddField(
            model_name="online",
            name="company",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
